### ISSUE TITLE
change file name

### ISSUE THREAD

**Issue by pete-hulson** [BenWilliams-NOAA/afscassess#1]
https://github.com/BenWilliams-NOAA/afscassess/blob/44a43b3f964c369eb7fd00cc63b05c84b064248b/R/inputs.R#L133

this gets written out by afscdata into the raw folder as "goa_total_bts_biomass_data.csv", so, need to change "goa_ts_biomass_data.csv" here to "goa_total_bts_biomass_data.csv"

**Comment by BenWilliams-NOAA** [comment]
fixed and includes other survey options
