### ISSUE TITLE
proj issue

### ISSUE THREAD

**Issue by BenWilliams-NOAA** [BenWilliams-NOAA/afscassess#10]
https://github.com/BenWilliams-NOAA/afscassess/blob/c4ca09669f0dc5299da8d463dec98ae4bf038b82/R/outputs.R#L967

@pete-hulson this has 5 years of catch data, the switch at the top says 3 or 4 - in the main branch i have  [function ](https://github.com/BenWilliams-NOAA/afscassess/blob/main/R/proj.R) that has a [switch ](https://github.com/BenWilliams-NOAA/afscassess/blob/9e7f7beaa7bdcbea8813a85e2b517b1f68fd69ec/R/proj.R#L224) so it can account for assessment scenarios that differ from every other year. - doubt it blows anything up, but worth knowing.

**Comment by pete-hulson** [comment]
ah yeah, good point, it should just be 4 years worth of catch (in the off year). but, don't think it would change anything in this case, as you're not producing the scenario table in the off year assessment (only place i could think of where it would change something)
