### ISSUE TITLE
I think this dat file should be *_bts_sizecomp_data.csv

### ISSUE THREAD

**Issue by KristenOmori-NOAA** [BenWilliams-NOAA/afscassess#21]
https://github.com/BenWilliams-NOAA/afscassess/blob/797b5547991962bfe21b03ecebc7317132abad7d/R/inputs.R#L689

I think this *_bts_length_data.csv should be changed to the *_bts_sizecomp_data.csv (do the df uses the  *_bts_sizecomp_data.csv, while the dat uses the *_bts_length_data.csv)

**Comment by BenWilliams-NOAA** [comment]
fixed, thanks!
