### ISSUE TITLE
Add area to the read in data file name

### ISSUE THREAD

**Issue by KristenOmori-NOAA** [BenWilliams-NOAA/afscassess#24]
https://github.com/BenWilliams-NOAA/afscassess/blob/fc642b8d007f4fcb828a897bbce6420d36903bd9/R/inputs.R#L350

It is trying to call 'bts_specimen_data.csv' , but the file name has now changed to area*_bts_specimen_data.csv (e.g., goa_bts_specimen_data.csv)

**Comment by BenWilliams-NOAA** [comment]
fixed, but i recommend using https://github.com/BenWilliams-NOAA/saa
