### ISSUE TITLE
Change file name from fsh_catch.csv to fish_catch.csv

### ISSUE THREAD

**Issue by KristenOmori-NOAA** [BenWilliams-NOAA/afscassess#28]
https://github.com/BenWilliams-NOAA/afscassess/blob/bd40c6a4fa7c61ce1c671fd5954e2a7a5b5d3305/R/proj.R#L98

Can you change the csv fishery catch file to fish_catch.csv?

**Comment by BenWilliams-NOAA** [comment]
done
